import copy
import os

import numpy as np
import matplotlib.pyplot as plt

from dataset import load_all_runs, load_dataset, FEATURE_COLUMNS, LABEL_COLUMN
from perceptron import standardize
from mlp import MLP
from metrics import binary_metrics

# The sim2real experiment: is cheap simulated data worth anything when
# real wafers are expensive?
#
#   digital twin : graph/run_*       (our simulator, imperfect physics)
#   real fab     : graph/real/run_*  (shifted physics + noisier testers,
#                                     generated by `main.py --real`)
#
# Three ways to build the real fab's EDS model, all scored on held-out
# REAL runs:
#   scratch    - train only on the few real wafers you can afford
#   zero-shot  - train only on synthetic data, deploy as-is
#   fine-tune  - pretrain on synthetic, then adapt on the few real wafers
#
# If fine-tune beats both, the thesis holds: simulation substitutes for
# most - not all - of the expensive real data.

MLP_KW = dict(hidden=(16,), fail_weight=5.0)
BUDGETS = [250, 1000, 4000, 16000]   # real wafers you can "afford"
REPEATS = 10                         # seeds per budget; reported as mean +- std
                                     # so the gaps below can be read against
                                     # the run-to-run spread rather than taken
                                     # as exact figures
OUT_PATH = "graph/ml/sim2real.png"

# Okabe-Ito
SCRATCH_COLOR = "#E69F00"
FINETUNE_COLOR = "#0072B2"
ZEROSHOT_COLOR = "#009E73"
ORACLE_COLOR = "#999999"


def f1_on(model, X, y, mean, std):
    X_std, _, _ = standardize(X, mean, std)
    return binary_metrics(y, model.predict(X_std))


def train_scratch(X, y, seed):
    model = MLP(n_features=X.shape[1], seed=seed, **MLP_KW)
    Xs, mean, std = standardize(X)
    model.fit(Xs, y, epochs=60, batch_size=min(256, len(X)), verbose=False)
    return model, mean, std


def fine_tune(pretrained, X, y, mean, std, seed):
    model = copy.deepcopy(pretrained)
    model.seed = seed
    model.lr = 0.02          # small steps: adapt, don't forget
    Xs, _, _ = standardize(X, mean, std)   # scale exactly like pretraining
    model.fit(Xs, y, epochs=20, batch_size=min(256, len(X)), verbose=False)
    return model


if __name__ == "__main__":

    # ---- data -------------------------------------------------------
    X_syn, y_syn = load_dataset("graph")

    real = load_all_runs("graph/real")
    real_runs = sorted(real["Run"].unique())
    if len(real_runs) < 2:
        raise SystemExit(
            "Need at least 2 real runs (1 to adapt on + 1 to test on). "
            "Generate them with: python3 main.py --real"
        )

    # first real run = the wafers we may buy; the rest = the exam
    pool = real[real["Run"] == real_runs[0]]
    test = real[real["Run"] != real_runs[0]]
    X_pool = pool[FEATURE_COLUMNS].to_numpy()
    y_pool = pool[LABEL_COLUMN].astype(int).to_numpy()
    X_test = test[FEATURE_COLUMNS].to_numpy()
    y_test = test[LABEL_COLUMN].astype(int).to_numpy()

    print(f"synthetic train : {len(X_syn)} wafers ({X_syn.shape[1]} features)")
    print(f"real pool       : {len(X_pool)} wafers ({real_runs[0]})")
    print(f"real test       : {len(X_test)} wafers "
          f"({', '.join(real_runs[1:])})")
    print()

    # ---- pretrain on synthetic (the digital twin's model) -----------
    print("pretraining on synthetic data ...")
    pretrained = MLP(n_features=X_syn.shape[1], seed=0, **MLP_KW)
    X_syn_std, syn_mean, syn_std = standardize(X_syn)
    pretrained.fit(X_syn_std, y_syn, epochs=30, verbose=False)

    zero_shot = f1_on(pretrained, X_test, y_test, syn_mean, syn_std)
    print(f"zero-shot on real test : F1 {zero_shot['f1'] * 100:.2f}% "
          f"(recall {zero_shot['recall'] * 100:.2f}%)")

    # ---- upper reference: all 20k real wafers, from scratch ---------
    # Repeated over seeds like the budget sweep below: the headline claim
    # ("a little real data + synthetic pretraining beats the full real
    # pool") is a comparison against THIS number, so it needs a spread to
    # be read against, not a single draw.
    oracle_scores = []
    for rep in range(REPEATS):
        m, om, os_ = train_scratch(X_pool, y_pool, seed=rep)
        oracle_scores.append(f1_on(m, X_test, y_test, om, os_)["f1"])
    oracle_mean = float(np.mean(oracle_scores))
    oracle_sd = float(np.std(oracle_scores, ddof=1))
    print(f"oracle (all {len(X_pool)} real) : F1 {oracle_mean * 100:.2f} "
          f"+- {oracle_sd * 100:.2f}%")
    print()

    # ---- budget sweep ------------------------------------------------
    scratch_f1, finetune_f1 = [], []
    scratch_sd, finetune_sd = [], []

    print(f"{'real wafers':>12} | {'scratch F1':>16} | {'fine-tune F1':>16}")
    for n in BUDGETS:
        s_scores, f_scores = [], []
        for rep in range(REPEATS):
            rng = np.random.default_rng(100 + rep)
            idx = rng.choice(len(X_pool), size=n, replace=False)
            Xb, yb = X_pool[idx], y_pool[idx]

            m, mm, ms = train_scratch(Xb, yb, seed=rep)
            s_scores.append(f1_on(m, X_test, y_test, mm, ms)["f1"])

            m = fine_tune(pretrained, Xb, yb, syn_mean, syn_std, seed=rep)
            f_scores.append(f1_on(m, X_test, y_test, syn_mean, syn_std)["f1"])

        scratch_f1.append(np.mean(s_scores))
        finetune_f1.append(np.mean(f_scores))
        scratch_sd.append(np.std(s_scores, ddof=1))
        finetune_sd.append(np.std(f_scores, ddof=1))
        print(f"{n:>12} | {scratch_f1[-1] * 100:7.2f} +- {scratch_sd[-1] * 100:4.2f}% "
              f"| {finetune_f1[-1] * 100:7.2f} +- {finetune_sd[-1] * 100:4.2f}%")

    # ---- figure ------------------------------------------------------
    fig, ax = plt.subplots(figsize=(8, 5.5))

    ax.errorbar(BUDGETS, np.array(scratch_f1) * 100,
                yerr=np.array(scratch_sd) * 100, fmt="o-", capsize=4,
                color=SCRATCH_COLOR, lw=2,
                label="scratch (real data only)")
    ax.errorbar(BUDGETS, np.array(finetune_f1) * 100,
                yerr=np.array(finetune_sd) * 100, fmt="o-", capsize=4,
                color=FINETUNE_COLOR, lw=2,
                label="fine-tuned (synthetic pretrain + real)")
    ax.axhline(zero_shot["f1"] * 100, ls="--", color=ZEROSHOT_COLOR,
               lw=1.5, label="zero-shot (synthetic only)")
    ax.axhline(oracle_mean * 100, ls=":", color=ORACLE_COLOR,
               lw=1.5, label=f"oracle (all {len(X_pool):,} real wafers)")
    ax.axhspan((oracle_mean - oracle_sd) * 100,
               (oracle_mean + oracle_sd) * 100,
               color=ORACLE_COLOR, alpha=0.15, lw=0)

    ax.set_xscale("log")
    ax.set_xticks(BUDGETS, [f"{n:,}" for n in BUDGETS])
    ax.set_xlabel("Real wafers available for training")
    ax.set_ylabel("F1 on held-out real runs (fail class, %)")
    ax.set_title("sim2real: synthetic pretraining vs real-data budget\n"
                 f"(mean +- sd over {REPEATS} seeds; real fab has shifted "
                 "physics + noisier testers)")
    ax.legend(loc="lower right", fontsize=9)

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    fig.tight_layout()
    fig.savefig(OUT_PATH, dpi=150)
    print()
    print(f"saved {OUT_PATH}")
